### PR TITLE
Open engine: refuse an out-of-range embed token, and unblock the standalone CLI build

### PR DESCRIPTION
**Pull request by vegah**
Two independent fixes found while working on #32.

**`Q4NX.embed()` had no bounds check.** A token id past the end of
`model.embed_tokens.weight` read whatever bytes follow the tensor in the
container and returned them as an embedding — no error, plausible-looking
values. It now refuses, naming the id and the table size.

**`build.cmd` was missing `DISABLE_ABI_CHECK=1`**, which `CMakeLists.txt`'s
`flm` target already passes. Without it `xrt/detail/abi.h` wants a generated
`version-slim.h` that a raw XRT source checkout never produces, and `cl` fails
with C1083 before reaching any of this file's own code.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by Atomic-Germ** [comment]
Can you check this again #47 (Full CMake Build system) so we don't conflict? I believe I caught this in mine but it could be windows specific.

**Comment by vegah** [comment]
Checked against #47 — you did catch it, for CMake: `src/CMakeLists.txt:490` and the three test `CMakeLists.txt` all define `DISABLE_ABI_CHECK=1`, so every CMake-driven build is covered.

`src/open_qwen36/build.cmd` is the gap. It is not a CMake build — four raw `cl` invocations — and none of them carries the flag. Windows-specific, as you guessed, since it is a `.cmd`.

Reproduced on `main` today against a raw `C:\dev\XRT` checkout (no XRT build run in it, so the generated `version-slim.h` does not exist), compiling `core.cpp` with the exact flags `build.cmd` uses:

```
without the flag:  fatal error C1083: Cannot open include file:
                   'xrt/detail/version-slim.h'   [xrt/detail/abi.h(8)]
with the flag:     compiles OK
```

`abi.h` line 7 is `#if !defined(DISABLE_ABI_CHECK)`, so the include is skipped entirely when it is set.

No conflict with #47: this PR touches only the fourth `cl` line, the CLI — the one invocation of the four that takes `/I "%XRT_INCLUDE_DIR%"`. The other three build unit tests that need no XRT, as the script's own comment already says.

The Copilot point on `q4nx.py` is addressed in the branch as well: the `assert` is now a `raise IndexError` (an assert disappears under `python -O`), and `hidden` is validated against the embedding table's own row width rather than trusted.

— Claude, on behalf of @vegah

**Comment by vegah** [comment]
Fair point, and the claim behind it was right: nothing called `Q4NX.embed()` at all. Its only caller is `open_kernels/model/make_decode.py`, so the guard could have been removed or inverted without a single test failing.

Added `specs/open-engine/tests/test_q4nx_embed.py` — nine cases on a container the test builds itself (eight bytes of header length, the safetensors-shaped JSON, then the rows), so no model file is needed:

- every row reads back exactly what was written, through the bf16 round trip
- **both boundaries**: `0` and `vocab_size - 1` must *work* — that is what a guard written `0 < token` or `token <= vocab_size` gets wrong while still passing the middle of the range
- `-1`, `vocab_size` and `vocab_size + 1000` must raise `IndexError`, and the message must name the range
- a `hidden` that is not the row width must raise `ValueError`, including the `hidden=2048` default on a table of another width — the case the token check alone does not catch, since it reads a correctly shaped vector from the wrong offset for a valid token
- the guards fire before any read, checked against a deliberately truncated container

The tests were verified to **fail against the unguarded version**: swapping in `main`'s `embed()` fails 6 of the 9, and the 3 that still pass are the happy-path ones that should pass either way. A regression test nobody has seen fail is not evidence that it would catch anything.

Full spec suite: 192 passed, 1 skipped.

— Claude, on behalf of @vegah

**Review by Atomic-Germ — APPROVED** [review]
